# ref: https://github.com/conventional-changelog/commitlint/blob/4360d5/.circleci/config.yml
version: 2.1

commands:
  update-yarn:
    steps:
      - run:
          name: Update yarn
          command: yarn global add yarn@latest
  install:
    steps:
      - run:
          name: Install dependencies
          command: yarn install
  build:
    steps:
      - run:
          name: Build packages
          command: yarn build
  tsc:
    steps:
      - run:
          name: Type Check
          command: yarn tsc
  lint:
    steps:
      - run:
          name: Check syntax by eslint
          command: yarn lint
  env:
    steps:
      - run:
          name: Setup custom enviroment variables
          command: echo 'export echo="Hello, Jest!"' >> $BASH_ENV
  jest:
    steps:
      - run:
          name: Run jest
          command: yarn jest
  save-cache:
    steps:
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  run-node:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - env
      - update-yarn
      - install
      - build
      - tsc
      - jest
      - lint
      - save-cache
jobs:
  v10:
    docker:
      - image: node:10.15.2
    steps:
      - run-node

workflows:
  node:
    jobs:
      - v10
